# Generated by Django 4.0.6 on 2022-09-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_ticker_stock_symbol'),
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceTicker',
            new_name='Ticker',
        ),
        migrations.AlterModelTable(
            name='ticker',
            table='tbl_ticker',
        ),
    ]
