# Generated by Django 4.0.6 on 2022-09-01 13:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rest.common.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_rename_ticker_stock_symbol'),
        ('account', '0002_alter_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially filled'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('volume', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'db_table': 'tbl_order',
            },
            bases=(models.Model, rest.common.mixins.UpdateMixin),
        ),
    ]
