# Generated by Django 4.0.6 on 2022-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('pe', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('pb', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('de', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'tbl_stock',
            },
        ),
    ]
